// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgSW0jmXxeqv7GD4a-jbKOsdOTPx2lpYM',
    appId: '1:28614005570:web:0a7d148154d331d1aa6edb',
    messagingSenderId: '28614005570',
    projectId: 'bookstore-e2558',
    authDomain: 'bookstore-e2558.firebaseapp.com',
    storageBucket: 'bookstore-e2558.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6ZiIkGRU3dIrGVzAMZZLvdqlIEgvWvg',
    appId: '1:28614005570:android:04c17473439be61daa6edb',
    messagingSenderId: '28614005570',
    projectId: 'bookstore-e2558',
    storageBucket: 'bookstore-e2558.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqkFwgrw_VlWqtayH5dmSWzRJr52-XaTY',
    appId: '1:28614005570:ios:e552e0a123e4a143aa6edb',
    messagingSenderId: '28614005570',
    projectId: 'bookstore-e2558',
    storageBucket: 'bookstore-e2558.appspot.com',
    iosBundleId: 'com.example.groceryShoppingApp',
  );
}
